<?php


/**
 * 快递查询
 * @param $invoice_no
 * @param $shipping_name
 * @return bool|mixed
 */
function kuaidi($invoice_no, $shipping_name) {
    switch ($shipping_name) {
        case '中国邮政':$logi_type = 'ems';
            break;
        case '申通':
        case '申通快递':$logi_type = 'shentong';
            break;
        case '顺丰':$logi_type = 'shunfeng';
            break;
        case '韵达快运':$logi_type = 'yunda';
            break;
        case '天天快递':$logi_type = 'tiantian';
            break;
        case '圆通速递':$logi_type = 'yuantong';
            break;
        case '中通速递':$logi_type = 'zhongtong';
            break;
        case 'ems快递':$logi_type = 'ems';
            break;
        case '汇通快运':$logi_type = 'huitongkuaidi';
            break;
        case '全峰快递':$logi_type = 'quanfengkuaidi';
            break;
        case '宅急送':$logi_type = 'zhaijisong';
            break;
        case '安信达':$logi_type = 'anxindakuaixi';
            break;
        case 'bht':$logi_type = 'bht';
            break;
        case '百福东方国际物流':$logi_type = 'baifudongfang';
            break;
        case '中国东方（COE）':$logi_type = 'coe';
            break;
        case '大田物流':$logi_type = 'datianwuliu';
            break;
        case '德邦物流':$logi_type = 'debangwuliu';
            break;
        case 'dhl':$logi_type = 'dhl';
            break;
        case 'dpex':$logi_type = 'dpex';
            break;
        case 'd速快递':$logi_type = 'dsukuaidi';
            break;
        case '递四方':$logi_type = 'disifang';
            break;
        case 'fedex（国外）':$logi_type = 'fedex';
            break;
        case '飞康达物流':$logi_type = 'feikangda';
            break;
        case '飞快达':$logi_type = 'feikuaida';
            break;
        case '国通快递':$logi_type = 'guotongkuaidi';
            break;
        case '港中能达物流':$logi_type = 'ganzhongnengda';
            break;
        case '广东邮政物流':$logi_type = 'guangdongyouzhengwuliu';
            break;
        case '共速达':$logi_type = 'gongsuda';
            break;
        case '恒路物流':$logi_type = 'hengluwuliu';
            break;
        case '华夏龙物流':$logi_type = 'huaxialongwuliu';
            break;
        case '山东海红':$logi_type = 'haihongwangsong';
            break;
        case '海外环球':$logi_type = 'haiwaihuanqiu';
            break;
        case '佳怡物流':$logi_type = 'jiayiwuliu';
            break;
        case '京广速递':$logi_type = 'jinguangsudikuaijian';
            break;
        case '急先达':$logi_type = 'jixianda';
            break;
        case '佳吉物流':$logi_type = 'jiajiwuliu';
            break;
        case '加运美物流':$logi_type = 'jiayunmeiwuliu';
            break;
        case '金大物流':$logi_type = 'jindawuliu';
            break;
        case '嘉里大通':$logi_type = 'jialidatong';
            break;
        case '晋越快递':$logi_type = 'jinyuekuaidi';
            break;
        case '快捷速递':$logi_type = 'kuaijiesudi';
            break;
        case '联邦快递（国内）':$logi_type = 'lianbangkuaidi';
            break;
        case '联昊通物流':$logi_type = 'lianhaowuliu';
            break;
        case '龙邦物流':$logi_type = 'longbanwuliu';
            break;
        case '立即送':$logi_type = 'lijisong';
            break;
        case '乐捷递':$logi_type = 'lejiedi';
            break;
        case '美国快递':$logi_type = 'meiguokuaidi';
            break;
        case '门对门':$logi_type = 'menduimen';
            break;
        case 'OCS':$logi_type = 'ocs';
            break;
        case '全晨快递':$logi_type = 'quanchenkuaidi';
            break;
        case '全际通物流':$logi_type = 'quanjitong';
            break;
        case '全日通快递':$logi_type = 'quanritongkuaidi';
            break;
        case '全一快递':$logi_type = 'quanyikuaidi';
            break;
        case '如风达':$logi_type = 'rufengda';
            break;
        case '三态速递':$logi_type = 'santaisudi';
            break;
        case '盛辉物流':$logi_type = 'shenghuiwuliu';
            break;
        case '速尔物流':$logi_type = 'suer';
            break;
        case '盛丰物流':$logi_type = 'shengfengwuliu';
            break;
        case '赛澳递':$logi_type = 'saiaodi';
            break;
        case '天地华宇':$logi_type = 'tiandihuayu';
            break;
        case 'tnt':$logi_type = 'tnt';
            break;
        case 'ups':$logi_type = 'ups';
            break;
        case '万家物流':$logi_type = 'wanjiawuliu';
            break;
        case '万象物流':$logi_type = 'wanxiangwuliu';
            break;
        case '新邦物流':$logi_type = 'xinbangwuliu';
            break;
        case '信丰物流':$logi_type = 'xinfengwuliu';
            break;
        case '亚风速递':$logi_type = 'yafengsudi';
            break;
        case '一邦速递':$logi_type = 'yibangwuliu';
            break;
        case '优速物流':$logi_type = 'youshuwuliu';
            break;
        case '邮政包裹挂号信':$logi_type = 'youzhengguonei';
            break;
        case '邮政国际包裹挂号信':$logi_type = 'youzhengguoji';
            break;
        case '源伟丰快递':$logi_type = 'yuanweifeng';
            break;
        case '元智捷诚快递':$logi_type = 'yuanzhijiecheng';
            break;
        case '运通快递':$logi_type = 'yuntongkuaidi';
            break;
        case '越丰物流':$logi_type = 'yuefengwuliu';
            break;
        case '源安达':$logi_type = 'yuananda';
            break;
        case '银捷速递':$logi_type = 'yinjiesudi';
            break;
        case '中邮物流':$logi_type = 'zhongyouwuliu';
            break;
        case '忠信达':$logi_type = 'zhongxinda';
            break;
        case '芝麻开门':$logi_type = 'zhimakaimen';
            break;
        case '增益速递':$logi_type = 'zengyisudi';
            break;
    }
    if(empty($logi_type)){
        return false;
    }
    $kurl = 'http://www.kuaidi100.com/query?type=' . $logi_type . '&postid=' . $invoice_no;
    $get_content = file_get_contents($kurl);
    $data = json_decode($get_content,true);
    return $data;
}
